apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app-deployment
  labels:
    app: flask-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: hackler254/simple-flask-app:latest
        ports:
        - containerPort: 5000
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer  
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000