name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: 
          docker build -t hackler254/simple-flask-app:latest .
          docker push hackler254/simple-flask-app:latest

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push to DockerHub
      run: docker push hackler254/simple-flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Set up Kubernetes cluster with Kind
      run: kind create cluster --name kind

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Get cluster info
      run: kubectl cluster-info --context kind

    - name: Load Docker image into Kind
      run: kind load docker-image hackler254/simple-flask-app:latest --name kind

    - name: Deploy to Kind cluster
      run: |
        kubectl apply -f k8s/app-deployment.yaml
        

    - name: Get Service info
      run: kubectl get services

    - name: Clean up Kind cluster
      if: always()
      run: kind delete cluster --name kind